apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: 192.168.56.70
      user: vagrant
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: controller
    privateInterface: enp0s8
    privateAddress: 192.168.56.70
  - ssh:
      address: 192.168.56.71
      user: vagrant
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
    privateInterface: enp0s8
    privateAddress: 192.168.56.71
  - ssh:
      address: 192.168.56.72
      user: vagrant
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
    privateInterface: enp0s8
    privateAddress: 192.168.56.72
  - ssh:
      address: 192.168.56.73
      user: vagrant
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
    privateInterface: enp0s8
    privateAddress: 192.168.56.73
  k0s:
    version: v1.32.1+k0s.0
    config:
      spec:
        api:
          externalAddress: 192.168.56.70
          sans:
          - 192.168.56.70
#        network:
#          nodeLocalLoadBalancing:
#            enabled: true
#            type: EnvoyProxy
        extensions:
          helm:
            concurrencyLevel: 1
            repositories:
            - name: traefik
              url: https://traefik.github.io/charts
            - name: longhorn
              url: https://charts.longhorn.io
            - name: ingress-nginx
              url: https://kubernetes.github.io/ingress-nginx
            - name: metallb
              url: https://metallb.github.io/metallb
            - name: bitnami
              url: https://charts.bitnami.com/bitnami
            - name: jetstack
              url: https://charts.jetstack.io
            - name: ingress-nginx
              url: https://kubernetes.github.io/ingress-nginx
            charts:
            - name: traefik
              chartname: traefik/traefik
              version: "34.2.0"
              namespace: traefik
              order: 30
            - name: ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              namespace: ingress-nginx
              version: "4.12.0"
              order: 40
            - name: longhorn
              chartname: longhorn/longhorn
              version: "1.8.0"
              namespace: longhorn-system
              order: 10
            - name: metallb
              chartname: metallb/metallb
              version: "0.14.8"
              namespace: metallb-system
              order: 20
            - name: certmanager
              chartname: jetstack/cert-manager
              version: "v1.17.0"
              namespace: cert-manager
              order: 50
