apiVersion: v1
kind: Namespace
metadata:
  name: dummy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-web-server
  namespace: dummy
spec:
  selector:
    matchLabels:
      app: dummy-web
  template:
    metadata:
      labels:
        app: dummy-web
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.53-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-web-server-service
  namespace: dummy
spec:
  selector:
    app: dummy-web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-web-server-ingress
  namespace: dummy
spec:
  ingressClassName: nginx
  rules:
  - host: vg-dummy.fiks.im
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dummy-web-server-service
            port:
              number: 5000
